WMMCRCNational/Models/Chapter.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMMCRCNational.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Chapter
    {
        [Key]
        public int ChapterId { get; set; }

        [StringLength(250)]
        public string ChapterName { get; set; }

        [StringLength(150)]
        public string ChapterNickName { get; set; }

        public int? ClubHouseAddressID { get; set; }

        [Column(TypeName = "date")]
        public DateTime? DateModified { get; set; }

        [Column(TypeName = "date")]
        public DateTime? DateCreated { get; set; }

        public string GoogleLink { get; set; }

        [Display(Name = "Is Active")]
        public bool Active { get; set; }
        [NotMapped]
        public string activeValue { get; set; }
    }

}

WMMCRCNational/Controllers/ChaptersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WMMCRCNational.Helpers;

namespace WMMCRCNational.Models
{
    public class ChaptersController : Controller
    {
        private WMMCRC db = new WMMCRC();
        private bool admin { get; set; }
        private bool roadCaptain { get; set; }
        private bool member { get; set; }
        private int chapterId { get; set; }

        // GET: Chapters
        //        [Authorize]
        public ActionResult Index(string active)
        {
            CheckSecurity();

            FillDropDowns();
            List<Chapter> chapters = new List<Chapter>();
            if (active == null) active = "True";
            chapters = Helpers.Chapters.GetChapters(db, active);

            foreach (Chapter ch in chapters)
            {
                if (ch.Active)
                { ch.activeValue = "True"; }
                else
                { ch.activeValue = "False"; }

            }
            return View(chapters);
        }

       
        // GET: Chapters/Details/5
        //      [Authorize]
        public ActionResult Details(int? id)
        {
            CheckSecurity();
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            ChapterDetails cd = new ChapterDetails();

            cd.Chapters = (from ch in db.Chapters
                           where ch.ChapterId == id
                           select ch).ToList();

            cd.ChapterAddresses = (from a in db.ChapterAddresses
                                   where a.ChapterId == id
                                   select a).ToList();

            var stateid = (from s in cd.ChapterAddresses
                           select s.StateId.Value).FirstOrDefault();

            var stateName = from a in db.States
                            where a.Id == stateid
                            select a.Name;

            cd.State = stateName.FirstOrDefault();

            if (cd == null)
            {
                return HttpNotFound();
            }
            return View(cd);
        }

        // GET: Chapters/Create
        [Authorize]
        public ActionResult Create()
        {
            CheckSecurity();
            //Security if not logged in then redirect
            if ((System.Web.HttpContext.Current.User.Identity.IsAuthenticated == false) || (!ViewBag.admin))
            {
                return RedirectToAction("AccessError", "Account");
            }
            return View();
        }

        // POST: Chapters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ChapterId,ChapterName,ChapterNickName,ClubHouseAddressID,DateModified,DateCreated,Active")] Chapter chapter)
        {
            CheckSecurity();
            //Security if not logged in then redirect
            if ((System.Web.HttpContext.Current.User.Identity.IsAuthenticated == false) || (!ViewBag.admin))
            {
                return RedirectToAction("AccessError", "Account");
            }

            chapter.DateModified = System.DateTime.Now;
            chapter.DateCreated = System.DateTime.Now;

            if (ModelState.IsValid)
            {

                db.Chapters.Add(chapter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chapter);
        }

        // GET: Chapters/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            CheckSecurity();
            //Security if not logged in then redirect
            if ((System.Web.HttpContext.Current.User.Identity.IsAuthenticated == false) || (!ViewBag.admin))
            {
                return RedirectToAction("AccessError", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            return View(chapter);
        }

        // POST: Chapters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ChapterId,ChapterName,ChapterNickName,ClubHouseAddressID,DateModified,DateCreated,Active,GoogleLink")] Chapter chapter)
        {
            CheckSecurity();
            //Security if not logged in then redirect
            if ((System.Web.HttpContext.Current.User.Identity.IsAuthenticated == false) || (!ViewBag.admin))
            {
                return RedirectToAction("AccessError", "Account");
            }

            chapter.DateModified = System.DateTime.Now;
            chapter.DateCreated = chapter.DateCreated;

            if (ModelState.IsValid)
            {
                db.Entry(chapter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chapter);
        }

        // GET: Chapters/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            CheckSecurity();
            //Security if not logged in then redirect
            if ((System.Web.HttpContext.Current.User.Identity.IsAuthenticated == false) || (!ViewBag.admin))
            {
                return RedirectToAction("AccessError", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chapter chapter = db.Chapters.Find(id);
            if (chapter == null)
            {
                return HttpNotFound();
            }
            return View(chapter);
        }

        // POST: Chapters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            CheckSecurity();
            //Security if not logged in then redirect
            if ((System.Web.HttpContext.Current.User.Identity.IsAuthenticated == false) || (!ViewBag.admin))
            {
                return RedirectToAction("AccessError", "Account");
            }

            Chapter chapter = db.Chapters.Find(id);

            DeleteChapterAddress(id);

            db.Chapters.Remove(chapter);
            db.SaveChanges();


            return RedirectToAction("Index");
        }

        private void DeleteChapterAddress(int chapterId)
        {
            CheckSecurity();
            var chapterAddressID = (from s in db.ChapterAddresses
                                    where s.ChapterId == chapterId
                                    select s.ChapterAddressId).FirstOrDefault();

            ChapterAddress chapterAddress = db.ChapterAddresses.Find(chapterAddressID);
            db.ChapterAddresses.Remove(chapterAddress);
            db.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult OpenGoogleMap(string MapUri)
        {

            return Redirect(MapUri);
        }

        private void FillDropDowns()
        {
            //Active dd

            //This is a great way to select the distinct Values to populate the DD
            //var activedd = new SelectList(db.Members.ToList(), "Active", "Active");
            //SelectList distinctActive = new SelectList(activedd.GroupBy( o => o.Value).Select(v => v.FirstOrDefault().Value.ToString()));

            List<string> activeList = new List<string>();
            activeList.Add("True");
            activeList.Add("False");
            activeList.Add("ALL");
            var rideYear = new SelectList(activeList);
            ViewData["ActiveDD"] = activeList;
            ViewBag.active = new SelectList(activeList);

        }
        private void CheckSecurity()
        {
            SecurityObjectWM secObj = GlobalHelper.SetSecurity(db);
            ViewBag.admin = secObj.adminRole;
            ViewBag.roadCaptain = secObj.roadCaptainRole;
            ViewBag.member = secObj.memberRole;
            chapterId = secObj.chapterId;

        }
    }
}

WMMCRCNational/Views/Chapters/Create.cshtml
@model WMMCRCNational.Models.Chapter

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DateCreated)

    <div class="form-horizontal">
        <h4>Chapters</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ChapterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChapterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChapterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChapterNickName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChapterNickName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChapterNickName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WMMCRCNational/Views/Chapters/Delete.cshtml
@model WMMCRCNational.Models.Chapter

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Chapter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChapterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChapterNickName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNickName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    @if (ViewBag.admin)
    {
        <input type="submit" value="Delete" class="btn btn-default" />
    }
        @Html.ActionLink("Back to List", "Index")
    </div>
    }
</div>

WMMCRCNational/Views/Chapters/Details.cshtml
@model WMMCRCNational.Models.ChapterDetails

@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Common Address</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chapter</h4>
        <hr />
        <div>
            @foreach (var item in Model.Chapters)
            {
                <div class="form-horizontal">
                    @Html.DisplayFor(modelItem => item.ChapterName)
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        @foreach (var itemA in Model.ChapterAddresses)
                        {
                            @Html.DisplayFor(modelItem => itemA.StreetAddress1)
                            <br />
                            if (!String.IsNullOrEmpty(itemA.StreetAddress2))
                            {
                                @Html.DisplayFor(modelItem => itemA.StreetAddress2)
                                <br />
                            }
                            @Html.DisplayFor(modelItem => itemA.City)
                            <br />
                            @Model.State
                            <br />
                            @Html.DisplayFor(modelItem => itemA.Zip)
                           
                        }
                    </div>
                </div>
            }

        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
    @if (ViewBag.admin)
    {
        @Html.ActionLink("      |       Edit Address ", "Edit", "ChapterAddresses", new { id = Model.Chapters.FirstOrDefault().ChapterId }, null)
    }
</div>

WMMCRCNational/Views/Chapters/Edit.cshtml
@model WMMCRCNational.Models.Chapter

@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><h2>Chapters Names </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Chapter</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ChapterId)
    @Html.HiddenFor(model => model.DateCreated)
    @Html.HiddenFor(model => model.ClubHouseAddressID)
    @Html.HiddenFor(model => model.GoogleLink)

    <div class="form-group">
        @Html.LabelFor(model => model.ChapterName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ChapterName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ChapterName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ChapterNickName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ChapterNickName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ChapterNickName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="dropdown-menu-left">
                @Html.DropDownListFor(model => model.Active, new SelectList(
                new[]
                {
                    new { Value = "true", Text = "Yes" },
                    new { Value = "false", Text = "No" },
                },
                "Value",
                "Text"
            ))
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WMMCRCNational/Views/Chapters/Index.cshtml
@model IEnumerable<WMMCRCNational.Models.Chapter>

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chapters List</h2>

@if (ViewBag.admin)
{
    <p>
        @Html.ActionLink("Create New Chapter", "Create")
    </p>
}


@using (Html.BeginForm("Index", "Chapters", FormMethod.Get))
{

    <div class="two-column">
        <label class="int-box">Active Chapters Selection:</label>
        @Html.DropDownList("active", ViewData["ActiveDD"] as SelectList, new { onChange = "changeTextboxes(this.value);" })

    </div>
    <br />
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ChapterName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChapterNickName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChapterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChapterNickName)
            </td>
            <td>
                @Html.DisplayFor(modelitem => item.activeValue)

            </td>

            <td>
                @if (ViewBag.admin)
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ChapterId })
                    <br />
                }

                @Html.ActionLink("View Details", "Details", new { id = item.ChapterId })
                <br />
                @Html.ActionLink(" Google Map", "OpenGoogleMap", new { MapUri = item.GoogleLink }, new { target = "_blank" })
            </td>
        </tr>
    }

</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")

    @Styles.Render("~/Content/jquery-ui.css")
    @Scripts.Render("~/Scripts/jquery-1.12.4.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")


    <script>

        function changeTextboxes(val) {

            var url = '/Chapters?active=' + val;
            window.location.href = url;
        }

    </script>
}