WMMCRCNational/Controllers/RidesReadOnlyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WMMCRCNational.Models;
using PagedList;
using System.Data.Entity.SqlServer;
using System.Web.UI.HtmlControls;

namespace WMMCRCNational.Views
{
    public class RidesReadOnlyController : Controller
    {
        public int? memberSelected { get; set; }
        private WMMCRC db = new WMMCRC();
        private int chapterId { get; set; }

        // GET: RidesReadOnly
        public ActionResult Index(string searchString, string currentFilter, int? page, int? MemberId, string years, string button, string chapter)
        {
            Rides_MembersModel viewModel = new Rides_MembersModel();


            if (Session["ChapterId"] != null && !string.IsNullOrEmpty(Session["ChapterId"].ToString()))
            {
                chapterId = Convert.ToInt32(Session["ChapterId"]);
            }
            else if(!string.IsNullOrEmpty(chapter) && chapter != null){
                
                chapterId = Convert.ToInt32(chapter);
            }

            FillDropDowns(null,chapterId);
            //Code added for Paging
            //The first time the page is displayed, or if the user hasn't clicked a paging or sorting link, all the parameters will be null.  If a paging link is clicked, the page variable will contain the page number to display.
            //A ViewBag property provides the view with the current sort order, because this must be included in the paging links in order to keep the sort order the same while paging:

            ViewBag.memberId = MemberId;
            ViewBag.searchYear = years;
            ViewBag.chapter = chapterId;

            //If years is null default to current year
            if (string.IsNullOrEmpty(years))
            {
                years = System.DateTime.Now.Year.ToString();
            }

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            //End of first set of code for paging

            IOrderedEnumerable<Ride> returnRides;

            // This Returns all the rides and the Clubhouse Names
            List<Ride> ridesList = Helpers.Rides.GetLisMemberNames(db, years, chapterId);

            // If the year is not specified then want to default to this years rides
            if (string.IsNullOrWhiteSpace(years))
            {
                List<Ride> rideListCurrentYear = Helpers.Rides.GetThisYearRides(ridesList);
                //This returns the list of rindes for a specific Member
                returnRides = Helpers.Rides.GetSearchView(MemberId, rideListCurrentYear);
            }
            else
            {
                //This returns the list of rindes for a specific Member
                returnRides = Helpers.Rides.GetSearchView(MemberId, ridesList);
            }

            if (!string.IsNullOrWhiteSpace(years))
            {
                returnRides = Helpers.Rides.GetSearchDateView(returnRides, years);
            }

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                returnRides = Helpers.Rides.GetSearchRideNotes(returnRides, searchString);
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(returnRides.ToPagedList(pageNumber, pageSize));

        }


        private void FillDropDowns(int? memberSelected,int? chapter)
        {
           
            if (Session["ChapterId"] != null && !string.IsNullOrEmpty(Session["ChapterId"].ToString()))
            {
                chapterId = Convert.ToInt32(Session["ChapterId"]);
            }

            //Chapters
            var chapterSearch = new SelectList(db.Chapters.ToList(), "ChapterId", "ChapterName");
            ViewData["ChapterDD"] = chapterSearch;
            ViewBag.chapter = new SelectList(chapterSearch);

            //Member dd
            var memberdd = (from a in db.Members
                            where a.Active == true
                            && a.ChapterId == chapterId
                            select a.FullName).FirstOrDefault();

            ViewData["MemberDD"] = memberdd;
            //using viewbag  
            ViewBag.memberdd = new SelectList(db.Members.ToList().Where(a => a.Active == true && a.ChapterId == chapterId), "MemberId", "FullName");
            if (memberSelected != null)
            {
                ViewBag.MemberId = memberSelected;
            }

            //Ride From dd
            var rideFromdd = new SelectList(db.Chapters.ToList(), "ChapterId", "ChapterName");
            ViewData["RideFromDD"] = rideFromdd;
            //RideToDD
            var rideTodd = new SelectList(db.Chapters.ToList(), "ChapterId", "ChapterName");
            ViewData["RideToDD"] = rideTodd;

            //Years
            List<string> years = new List<string>();
            years.Add("2017");
            years.Add("2018");
            years.Add("2019");
            years.Add("2020");
            years.Add("2021");
            years.Add("2022");
            years.Add("2023");
            years.Add("2024");
            years.Add("2025");
            var rideYear = new SelectList(years);
            ViewData["YearDD"] = years;
            ViewBag.years = new SelectList(years);
        }


        // GET: RidesReadOnly/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ride ride = db.Rides.Find(id);
            if (ride == null)
            {
                return HttpNotFound();
            }
            return View(ride);
        }

        // GET: RidesReadOnly/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RidesReadOnly/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RideId,MemberId,RideDate,RideFrom,RideTo,Miles,DateModified,DateCreated,Partial,VerifiableEvent,Cage,RideNotes")] Ride ride)
        {
            if (ModelState.IsValid)
            {
                db.Rides.Add(ride);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ride);
        }

        // GET: RidesReadOnly/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ride ride = db.Rides.Find(id);
            if (ride == null)
            {
                return HttpNotFound();
            }
            return View(ride);
        }

        // POST: RidesReadOnly/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RideId,MemberId,RideDate,RideFrom,RideTo,Miles,DateModified,DateCreated,Partial,VerifiableEvent,Cage,RideNotes")] Ride ride)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ride).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ride);
        }

        // GET: RidesReadOnly/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ride ride = db.Rides.Find(id);
            if (ride == null)
            {
                return HttpNotFound();
            }
            return View(ride);
        }

        // POST: RidesReadOnly/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ride ride = db.Rides.Find(id);
            db.Rides.Remove(ride);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WMMCRCNational/Views/RidesReadOnly/Create.cshtml
@model WMMCRCNational.Models.Ride

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ride</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Miles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Miles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Miles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Partial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Partial)
                    @Html.ValidationMessageFor(model => model.Partial, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerifiableEvent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VerifiableEvent)
                    @Html.ValidationMessageFor(model => model.VerifiableEvent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Cage)
                    @Html.ValidationMessageFor(model => model.Cage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WMMCRCNational/Views/RidesReadOnly/Delete.cshtml
@model WMMCRCNational.Models.Ride

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ride</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MemberId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Miles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Miles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Partial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Partial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerifiableEvent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerifiableEvent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideNotes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WMMCRCNational/Views/RidesReadOnly/Details.cshtml
@model WMMCRCNational.Models.Ride

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Ride</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MemberId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Miles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Miles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Partial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Partial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerifiableEvent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerifiableEvent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RideNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RideNotes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RideId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WMMCRCNational/Views/RidesReadOnly/Edit.cshtml
@model WMMCRCNational.Models.Ride

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ride</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RideId)

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Miles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Miles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Miles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Partial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Partial)
                    @Html.ValidationMessageFor(model => model.Partial, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerifiableEvent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VerifiableEvent)
                    @Html.ValidationMessageFor(model => model.VerifiableEvent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Cage)
                    @Html.ValidationMessageFor(model => model.Cage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RideNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RideNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RideNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WMMCRCNational/Views/RidesReadOnly/Index.cshtml
@model PagedList.IPagedList<WMMCRCNational.Models.Ride>

@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ride List</h2>


@using (Html.BeginForm("Index", "RidesReadOnly", FormMethod.Get))
{

    <div class="two-column">
        <label class="int-box">Active Chapters Selection:</label>
        @Html.DropDownList("chapter", ViewData["ChapterDD"] as SelectList, "Select Member", new { onChange = "changeTextboxes(this.value);" })
    </div>
    

    <div class="two-column">
        <label class="int-box">Find "Member Rides" by name:</label>
        @Html.DropDownList("MemberId", ViewData["MemberDD"] as SelectList, "Select Member")
    </div>

    <div class="two-column">
        <label class="int-box">Find "Member Rides" by Year:</label>
        @Html.DropDownList("years", ViewData["YearDD"] as SelectList, "Select Year")
        <label class="text-danger">&nbsp;&nbsp;&nbsp;* if no year select then default to the current year </label>
    </div>

    <div class="two-column">
        <label class="int-box">Search Ride Notes:</label>
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
    </div>
    <br />
    <div class="two-column">
        <input type="submit" value="Search" id="search" class="btn btn-default" />&nbsp;&nbsp;&nbsp;
        <input type="submit" value="Reset Search" id="reset" class="btn btn-default" />
    </div>
    <br />
}

<table class="table">
    <tr>
        <th>
            Member
        </th>
        <th>
            Ride From
        </th>
        <th>
            Ride To
        </th>
        <th>
            Miles
        </th>
        <th>
            Ride Date
        </th>
        <th>
            Ride Notes
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MemberName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RideFromName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.RideToName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Miles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RideDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RideNotes)
            </td>
            <td>
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.RideId })
                }

                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Details", "Details", new { id = item.RideId })
                }
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Delete", "Delete", new { id = item.RideId })
                }
            </td>



        </tr>
    }
</table>
<br />
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, MemberId = ViewBag.memberId, years = ViewBag.searchYear, chapter = ViewBag.chapter }))



        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
            @Scripts.Render("~/bundles/jqueryui")
            @Styles.Render("~/Content/cssjqryUi")
            @Scripts.Render("~/Scripts/jquery.validate.min.js")
            @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")

            @Styles.Render("~/Content/jquery-ui.css")
            @Scripts.Render("~/Scripts/jquery-1.12.4.js")
            @Scripts.Render("~/Scripts/jquery-ui.js")


            <script>


                //$(function () {
                //    $("#MemberId").change(function () {

                //        var val = $(this).val();
                //        $("#hidmemid").val(val);

                //        var test = $("#hidmemid").val();

                //        alert(test);


                //    });
                //});

                $(document).ready(function () {

                    //$("#create").click(function (event) {
                    //    event.preventDefault();

                    //    var val = $("#MemberId").val();
                    //    var url = '/Rides/Create/';

                    //    if ((val != null) && (val.length > 0))
                    //        var url = '/Rides/Create/' + val;

                    //    window.location.href = url;
                    //    //alert(val);
                    //});
                   
                    $("#reset").click(function (event) {
                       
                        event.preventDefault();
                        var url = '/RidesReadOnly';
                        window.location.href = url;
                        
                    });

                    $("#search").click(function (event) {
                        //event.preventDefault();
                      
                        var refresh = 0;

                        var ddmemvalue = $('#MemberId option:selected').val();
                        if (ddmemvalue.length == 0) {
                            //alert("no member value");
                            refresh = 1;
                        }
                        var ddyearvalue = $('#years option:selected').val();
                        if (ddyearvalue.length == 0) {
                            //alert("no years value");
                            refresh = refresh + 1;
                        }

                        var searchstringvalue = $('#searchString').val();
                        if (searchstringvalue.length == 0) {
                            //alert("no search string value");
                            refresh = refresh + 1;
                        }
                        
                        if (refresh == 3) {
                            var url = '/RidesReadOnly';
                            window.location.href = url;
                        }
                    });

                });



                function changeTextboxes(val) {

                    var url = '/RidesReadOnly?chapter=' + val;
                    window.location.href = url;
                }

            </script>
        }